### ISSUE TITLE
Goodreads redesign - initial feedback

### ISSUE THREAD

**Issue by michaelbrownsf** [andreastclair/tiy_assignments#4]
Font sizes need to be no less than 16 pixels or 1em.

On your icon set, have you tried just using the grey rather than the cutout version you're using? For me it makes the icons seem to vibrate on my screen.

Overall spacing seems solid and consistent.

**Comment by andreastclair** [comment]
Thanks Michael! I didn't know they were vibrating, I hate that. Tried a new approach that will hopefully fix the issue. And font sizes have been bumped up. Thanks for the feedback :)
