### ISSUE TITLE
Goodreads initial critique 

### ISSUE THREAD

**Issue by ChrisDJordan** [andreastclair/tiy_assignments#5]
The messge and send recomendation icon seem a little overwhelming compared to the rest of the layout. I miss the fox too! I undertand why you didn't go that route, but was kind of bummed. Overall it looks great, the header was a really great idea.

<img width="607" alt="screen shot 2015-07-13 at 12 56 38 pm" src="https://cloud.githubusercontent.com/assets/12628873/8656777/4bcce3d0-295f-11e5-8c87-bfcffc2179be.png">

**Comment by andreastclair** [comment]
I was pretty bummed that I couldn't make him fit anywhere! Maybe in another version... The envelope is totally overwhelming in this screenshot-it's supposed to just be a zoomed in view of what would happen if you clicked on the envelope next to the profile picture, dang you github! Thanks for the feedback and the extra set of eyes. Going in to look at yours now, sorry I forgot to do it earlier!
