### ISSUE TITLE
Critique and notes for GoodReads Comps July 13, 2015

### ISSUE THREAD

**Issue by fsanger** [andreastclair/tiy_assignments#7]
Home Page:
Heading bar works well, nice color choices.
Icon design is clear, though may need a little more contrast for icons on orange header bar.
Gray background may be a little too dark for good contrast.
Size of books in global/small view seems a bit large, especially with small amounts of text content.
Good use of the color bars/tags in the featured poll and quote of the day sections.

My Books:
The floating pop-up book description works well, but maybe on a white background to give it emphasis.
Smaller icons at bottom right...
Possibly integrate the bar/tags from featured poll to set off the My Shelves and Tools section menus.

Profile:
Need indication of where we are... via label, menu, in both small and large screen versions
Maybe the icon that also fills in in the book slot for achievement in reading could be smaller.
Also wonder if the gray background is necessary throughout... more white might brighten certain areas and brighten and focus eye on certain areas.
Send a Message/Send a Recommendation + envelope icon at bottom could be smaller.
Sidebars on right and left work well.

**Comment by andreastclair** [comment]
Thanks for the feedback Francois! It was very thorough and very helpful :)
