### ISSUE TITLE
Goodreads Mock Up Feedback

### ISSUE THREAD

**Issue by cczapski** [andreastclair/tiy_assignments#8]
You have a good consistency with spacing of your elements across your pages, but I think you could use some more spacing on your elements relative to their container or border. For example, at least double the amount of space your avatars and text have from the outer border of their containers. 

On your mobile version with the Amy Pohler book, it looks like you took the size of the screen and took that into better consideration when sizing elements on the page. You should mirror that across the other smaller versions of each page (i.e. make the books a bigger size, increase the size of the text).

Overall on your font sizes, I think they could get 2 - 4 pixels larger in size to make them easier to read.

All in all, your color scheme and unique header layout create a clean and fun vibe for the Goodreads site.

**Comment by andreastclair** [comment]
I went through and tried to give everything a bit more breathing room and bumped up all of my font sizes. Thanks for the extra set of eyes!
